services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      
      - .:/usr/src/app
    working_dir: /usr/src/app
    
    user: root
    
    command: sh -c "npm install && node app.js"
    
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: